# Generated by Django 6.0.3 on 2026-05-31 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_pricealert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricealert',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='pricealert',
            name='is_above',
        ),
        migrations.AddField(
            model_name='pricealert',
            name='condition',
            field=models.CharField(choices=[('above', 'Above'), ('below', 'Below')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricealert',
            name='triggered',
            field=models.BooleanField(default=False),
        ),
    ]
