# Generated by Django 6.0.3 on 2026-05-31 08:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_remove_pricealert_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pricealert',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='stock_symbol',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='Alert',
        ),
    ]
